from __future__ import annotations

from datetime import date
from decimal import Decimal
from typing import Protocol

from app.domain.entities import AuthUser, Credit, DictionaryEntry, Payment, Plan, User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: int) -> User | None: ...
    async def exists(self, user_id: int) -> bool: ...


class CreditRepository(Protocol):
    async def list_by_user(self, user_id: int) -> list[Credit]: ...
    async def sum_body_between(self, start: date, end: date) -> Decimal: ...
    async def monthly_stats(self, year: int) -> list[tuple[int, int, Decimal]]: ...


class PaymentRepository(Protocol):
    async def list_by_credit(self, credit_id: int) -> list[Payment]: ...
    async def list_by_credits(self, credit_ids: list[int]) -> list[Payment]: ...
    async def sum_between(self, start: date, end: date) -> Decimal: ...
    async def monthly_stats(self, year: int) -> list[tuple[int, int, Decimal]]: ...


class PlanRepository(Protocol):
    async def exists_for_period_category(self, period: date, category_id: int) -> bool: ...
    async def bulk_insert(self, plans: list[Plan]) -> None: ...
    async def list_up_to(self, check_date: date) -> list[Plan]: ...
    async def list_for_year(self, year: int) -> list[Plan]: ...


class DictionaryRepository(Protocol):
    async def list_all(self) -> list[DictionaryEntry]: ...
    async def get_by_name(self, name: str) -> DictionaryEntry | None: ...
    async def get_by_id(self, entry_id: int) -> DictionaryEntry | None: ...


class AuthUserRepository(Protocol):
    async def get_by_login(self, login: str) -> AuthUser | None: ...
    async def create(self, login: str, hashed_password: str) -> AuthUser: ...
